Removed gimp dependencies.
git-svn-id: svn+ssh://svn.rm.ingv.it/svn/teseo2/trunk@264 afdc3c29-bc1c-424d-8b75-1d331506fbbc

diff --git a/gtk-addons/configure b/gtk-addons/configure
--- a/gtk-addons/configure
+++ b/gtk-addons/configure
@@ -467,7 +467,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO SET_MAKE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP build build_cpu build_vendor build_os host host_cpu host_vendor host_os LN_S ECHO RANLIB ac_ct_RANLIB STRIP ac_ct_STRIP LIBTOOL NO_PREFIX_PACKAGE_DATA_DIR PACKAGE_DATA_DIR NO_PREFIX_PACKAGE_DOC_DIR PACKAGE_DOC_DIR NO_PREFIX_PACKAGE_PIXMAPS_DIR PACKAGE_PIXMAPS_DIR NO_PREFIX_PACKAGE_HELP_DIR PACKAGE_HELP_DIR NO_PREFIX_PACKAGE_MENU_DIR PACKAGE_MENU_DIR PKG_CONFIG GIMP_CFLAGS GIMP_LIBS GIMP_LIBDIR LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO SET_MAKE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP build build_cpu build_vendor build_os host host_cpu host_vendor host_os LN_S ECHO RANLIB ac_ct_RANLIB STRIP ac_ct_STRIP LIBTOOL NO_PREFIX_PACKAGE_DATA_DIR PACKAGE_DATA_DIR NO_PREFIX_PACKAGE_DOC_DIR PACKAGE_DOC_DIR NO_PREFIX_PACKAGE_PIXMAPS_DIR PACKAGE_PIXMAPS_DIR NO_PREFIX_PACKAGE_HELP_DIR PACKAGE_HELP_DIR NO_PREFIX_PACKAGE_MENU_DIR PACKAGE_MENU_DIR PKG_CONFIG GTK_CFLAGS GTK_LIBS GTK_LIBDIR LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -8432,7 +8432,7 @@ _ACEOF
 
 
 
-GIMP_REQUIRED_VERSION=2.2.0
+GTK_REQUIRED_VERSION=2.2.0
 
 
   succeeded=no
@@ -8488,32 +8488,32 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for gimp-2.0 >= $GIMP_REQUIRED_VERSION gimpui-2.0 >= $GIMP_REQUIRED_VERSION" >&5
-echo $ECHO_N "checking for gimp-2.0 >= $GIMP_REQUIRED_VERSION gimpui-2.0 >= $GIMP_REQUIRED_VERSION... $ECHO_C" >&6
+        echo "$as_me:$LINENO: checking for gtk+-2.0 >= $GTK_REQUIRED_VERSION" >&5
+        echo $ECHO_N "checking for gtk+-2.0 >= $GTK_REQUIRED_VERSION" >&6
 
-        if $PKG_CONFIG --exists "gimp-2.0 >= $GIMP_REQUIRED_VERSION gimpui-2.0 >= $GIMP_REQUIRED_VERSION" ; then
+        if $PKG_CONFIG --exists "gtk+-2.0 >= $GTK_REQUIRED_VERSION" ; then
             echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
+	    echo "${ECHO_T}yes" >&6
             succeeded=yes
 
-            echo "$as_me:$LINENO: checking GIMP_CFLAGS" >&5
-echo $ECHO_N "checking GIMP_CFLAGS... $ECHO_C" >&6
-            GIMP_CFLAGS=`$PKG_CONFIG --cflags "gimp-2.0 >= $GIMP_REQUIRED_VERSION gimpui-2.0 >= $GIMP_REQUIRED_VERSION"`
-            echo "$as_me:$LINENO: result: $GIMP_CFLAGS" >&5
-echo "${ECHO_T}$GIMP_CFLAGS" >&6
+            echo "$as_me:$LINENO: checking GTK_CFLAGS" >&5
+echo $ECHO_N "checking GTK_CFLAGS... $ECHO_C" >&6
+            GTK_CFLAGS=`$PKG_CONFIG --cflags "gtk+-2.0 >= $GTK_REQUIRED_VERSION"`
+            echo "$as_me:$LINENO: result: $GTK_CFLAGS" >&5
+echo "${ECHO_T}$GTK_CFLAGS" >&6
 
-            echo "$as_me:$LINENO: checking GIMP_LIBS" >&5
-echo $ECHO_N "checking GIMP_LIBS... $ECHO_C" >&6
-            GIMP_LIBS=`$PKG_CONFIG --libs "gimp-2.0 >= $GIMP_REQUIRED_VERSION gimpui-2.0 >= $GIMP_REQUIRED_VERSION"`
-            echo "$as_me:$LINENO: result: $GIMP_LIBS" >&5
-echo "${ECHO_T}$GIMP_LIBS" >&6
+            echo "$as_me:$LINENO: checking GTK_LIBS" >&5
+echo $ECHO_N "checking GTK_LIBS... $ECHO_C" >&6
+            GTK_LIBS=`$PKG_CONFIG --libs "gtk+-2.0 >= $GTK_REQUIRED_VERSION"`
+            echo "$as_me:$LINENO: result: $GTK_LIBS" >&5
+echo "${ECHO_T}$GTK_LIBS" >&6
         else
-            GIMP_CFLAGS=""
-            GIMP_LIBS=""
+            GTK_CFLAGS=""
+            GTK_LIBS=""
             ## If we have a custom action on failure, don't print errors, but
             ## do set a variable so people can do so.
-            GIMP_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "gimp-2.0 >= $GIMP_REQUIRED_VERSION gimpui-2.0 >= $GIMP_REQUIRED_VERSION"`
-            echo $GIMP_PKG_ERRORS
+            GTK_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "gtk+-2.0 >= $GTK_REQUIRED_VERSION"`
+            echo $GTK_PKG_ERRORS
         fi
 
 
@@ -8527,8 +8527,8 @@ echo "${ECHO_T}$GIMP_LIBS" >&6
   if test $succeeded = yes; then
      :
   else
-     { { echo "$as_me:$LINENO: error: Library requirements (gimp-2.0 >= $GIMP_REQUIRED_VERSION gimpui-2.0 >= $GIMP_REQUIRED_VERSION) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-echo "$as_me: error: Library requirements (gimp-2.0 >= $GIMP_REQUIRED_VERSION gimpui-2.0 >= $GIMP_REQUIRED_VERSION) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+     { { echo "$as_me:$LINENO: error: Library requirements (gtk+-2.0 >= $GTK_REQUIRED_VERSION) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (gtk+-2.0 >= $GTK_REQUIRED_VERSION) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
 
@@ -8536,7 +8536,7 @@ echo "$as_me: error: Library requirements (gimp-2.0 >= $GIMP_REQUIRED_VERSION gi
 
 
 
-GIMP_LIBDIR=`$PKG_CONFIG --variable=gimplibdir gimp-2.0`
+GTK_LIBDIR=`$PKG_CONFIG --variable=gtklibdir gtk+-2.0`
 
 
 
@@ -8553,21 +8553,6 @@ echo "${ECHO_T}$have_gtk_2_7" >&6
 if test "x$have_gtk_2_7" != "xyes"; then
   CPPFLAGS="$CPPFLAGS -DG_DISABLE_DEPRECATED -DGDK_DISABLE_DEPRECATED -DGTK_DISABLE_DEPRECATED"
 fi
-
-echo "$as_me:$LINENO: checking if GIMP is version 2.3.0 or newer" >&5
-echo $ECHO_N "checking if GIMP is version 2.3.0 or newer... $ECHO_C" >&6
-if $PKG_CONFIG --atleast-version=2.3.0 gimp-2.0; then
-  have_gimp_2_3=yes
-else
-  have_gimp_2_3=no
-fi
-echo "$as_me:$LINENO: result: $have_gimp_2_3" >&5
-echo "${ECHO_T}$have_gimp_2_3" >&6
-
-if test "x$have_gimp_2_3" != "xyes"; then
-  CPPFLAGS="$CPPFLAGS -DGIMP_DISABLE_DEPRECATED"
-fi
-
 
                     ac_config_files="$ac_config_files gtk-addons.pc gtk-addons-uninstalled.pc"
 
@@ -9250,9 +9235,9 @@ s,@PACKAGE_HELP_DIR@,$PACKAGE_HELP_DIR,;t t
 s,@NO_PREFIX_PACKAGE_MENU_DIR@,$NO_PREFIX_PACKAGE_MENU_DIR,;t t
 s,@PACKAGE_MENU_DIR@,$PACKAGE_MENU_DIR,;t t
 s,@PKG_CONFIG@,$PKG_CONFIG,;t t
-s,@GIMP_CFLAGS@,$GIMP_CFLAGS,;t t
-s,@GIMP_LIBS@,$GIMP_LIBS,;t t
-s,@GIMP_LIBDIR@,$GIMP_LIBDIR,;t t
+s,@GTK_CFLAGS@,$GTK_CFLAGS,;t t
+s,@GTK_LIBS@,$GTK_LIBS,;t t
+s,@GTK_LIBDIR@,$GTK_LIBDIR,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
