Introduced first plot\!
git-svn-id: svn+ssh://svn.rm.ingv.it/svn/teseo2/trunk@575 afdc3c29-bc1c-424d-8b75-1d331506fbbc

diff --git a/teseo-2/configure b/teseo-2/configure
--- a/teseo-2/configure
+++ b/teseo-2/configure
@@ -309,7 +309,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT PKG_CONFIG GIMP_CFLAGS GIMP_LIBS GIMP_LIBDIR GTKADDONS_CFLAGS GTKADDONS_LIBS GTKADDONS_LIBDIR NEWUOA_CFLAGS NEWUOA_LIBS NEWUOA_LIBDIR WIECHERT_CFLAGS WIECHERT_LIBS WIECHERT_LIBDIR GETTEXT_PACKAGE INTLTOOL_DESKTOP_RULE INTLTOOL_DIRECTORY_RULE INTLTOOL_KEYS_RULE INTLTOOL_PROP_RULE INTLTOOL_OAF_RULE INTLTOOL_PONG_RULE INTLTOOL_SERVER_RULE INTLTOOL_SHEET_RULE INTLTOOL_SOUNDLIST_RULE INTLTOOL_UI_RULE INTLTOOL_XAM_RULE INTLTOOL_KBD_RULE INTLTOOL_XML_RULE INTLTOOL_XML_NOMERGE_RULE INTLTOOL_CAVES_RULE INTLTOOL_SCHEMAS_RULE INTLTOOL_THEME_RULE INTLTOOL_EXTRACT INTLTOOL_MERGE INTLTOOL_UPDATE INTLTOOL_PERL ICONV MSGFMT MSGMERGE XGETTEXT mkdir_p USE_NLS GMSGFMT CATALOGS CATOBJEXT DATADIRNAME GMOFILES INSTOBJEXT INTLLIBS PO_IN_DATADIR_TRUE PO_IN_DATADIR_FALSE POFILES POSUB MKINSTALLDIRS LOCALEDIR DATADIR LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT PKG_CONFIG GIMP_CFLAGS GIMP_LIBS GIMP_LIBDIR GTKADDONS_CFLAGS GTKADDONS_LIBS GTKADDONS_LIBDIR GTKEXTRA_CFLAGS GTKEXTRA_LIBS GTKEXTRA_LIBDIR NEWUOA_CFLAGS NEWUOA_LIBS NEWUOA_LIBDIR WIECHERT_CFLAGS WIECHERT_LIBS WIECHERT_LIBDIR GETTEXT_PACKAGE INTLTOOL_DESKTOP_RULE INTLTOOL_DIRECTORY_RULE INTLTOOL_KEYS_RULE INTLTOOL_PROP_RULE INTLTOOL_OAF_RULE INTLTOOL_PONG_RULE INTLTOOL_SERVER_RULE INTLTOOL_SHEET_RULE INTLTOOL_SOUNDLIST_RULE INTLTOOL_UI_RULE INTLTOOL_XAM_RULE INTLTOOL_KBD_RULE INTLTOOL_XML_RULE INTLTOOL_XML_NOMERGE_RULE INTLTOOL_CAVES_RULE INTLTOOL_SCHEMAS_RULE INTLTOOL_THEME_RULE INTLTOOL_EXTRACT INTLTOOL_MERGE INTLTOOL_UPDATE INTLTOOL_PERL ICONV MSGFMT MSGMERGE XGETTEXT mkdir_p USE_NLS GMSGFMT CATALOGS CATOBJEXT DATADIRNAME GMOFILES INSTOBJEXT INTLLIBS PO_IN_DATADIR_TRUE PO_IN_DATADIR_FALSE POFILES POSUB MKINSTALLDIRS LOCALEDIR DATADIR LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -4434,7 +4434,53 @@ GTKADDONS_LIBDIR=`$PKG_CONFIG --variable=libdir gtk-addons`
 
 ##manually made end
 
+##manually made
+GTKEXTRA_REQUIRED_VERSION=0.15.0
 
+  succeeded=no
+
+        echo "$as_me:$LINENO: checking for gtkextra-2.0 >= $GTKEXTRA_REQUIRED_VERSION" >&5
+        echo $ECHO_N "checking for gtkextra-2.0 >= $GTKEXTRA_REQUIRED_VERSION... $ECHO_C" >&6
+
+
+	if $PKG_CONFIG --exists "gtkextra-2.0 >= $GTKEXTRA_REQUIRED_VERSION" ; then
+            echo "$as_me:$LINENO: result: yes" >&5
+            echo "${ECHO_T}yes" >&6
+            succeeded=yes
+
+            echo "$as_me:$LINENO: checking GTKEXTRA_CFLAGS" >&5
+            echo $ECHO_N "checking GTKEXTRA_CFLAGS... $ECHO_C" >&6
+            GTKEXTRA_CFLAGS=`$PKG_CONFIG --cflags "gtkextra-2.0 >= $GTKEXTRA_REQUIRED_VERSION"`
+            echo "$as_me:$LINENO: result: $GTKEXTRA_CFLAGS" >&5
+            echo "${ECHO_T}$GTKEXTRA_CFLAGS" >&6
+
+            echo "$as_me:$LINENO: checking GTKEXTRA_LIBS" >&5
+            echo $ECHO_N "checking GTKEXTRA_LIBS... $ECHO_C" >&6
+            GTKEXTRA_LIBS=`$PKG_CONFIG --libs "gtkextra-2.0 >= $GTKEXTRA_REQUIRED_VERSION"`
+            echo "$as_me:$LINENO: result: $GTKEXTRA_LIBS" >&5
+            echo "${ECHO_T}$GTKEXTRA_LIBS" >&6
+        else
+            GTKEXTRA_CFLAGS=""
+            GTKEXTRA_LIBS=""
+            ## If we have a custom action on failure, don't print errors, but
+            ## do set a variable so people can do so.
+            GTKEXTRA_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "gtkextra-2.0 >= $GTKEXTRA_REQUIRED_VERSION"`
+            echo $GTKEXTRA_PKG_ERRORS
+        fi
+
+
+  if test $succeeded = yes; then
+     :
+  else
+     { { echo "$as_me:$LINENO: error: Library requirements (gtkextra-2.0 >= $GTKEXTRA_REQUIRED_VERSION) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (gtkextra-2.0 >= $GTKEXTRA_REQUIRED_VERSION) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+GTKEXTRA_LIBDIR=`$PKG_CONFIG --variable=libdir gtkextra-2.0`
+
+
+##manually made end
 ##manually made
 NEWUOA_REQUIRED_VERSION=0.1
 
@@ -7153,6 +7199,9 @@ s,@GIMP_LIBDIR@,$GIMP_LIBDIR,;t t
 s,@GTKADDONS_CFLAGS@,$GTKADDONS_CFLAGS,;t t
 s,@GTKADDONS_LIBS@,$GTKADDONS_LIBS,;t t
 s,@GTKADDONS_LIBDIR@,$GTKADDONS_LIBDIR,;t t
+s,@GTKEXTRA_CFLAGS@,$GTKEXTRA_CFLAGS,;t t
+s,@GTKEXTRA_LIBS@,$GTKEXTRA_LIBS,;t t
+s,@GTKEXTRA_LIBDIR@,$GTKEXTRA_LIBDIR,;t t
 s,@NEWUOA_CFLAGS@,$NEWUOA_CFLAGS,;t t
 s,@NEWUOA_LIBS@,$NEWUOA_LIBS,;t t
 s,@NEWUOA_LIBDIR@,$NEWUOA_LIBDIR,;t t
