Added gtkdatabox package Added function void teseo_create_databox ()
git-svn-id: svn+ssh://svn.rm.ingv.it/svn/teseo2/trunk@624 afdc3c29-bc1c-424d-8b75-1d331506fbbc

diff --git a/teseo-dist/teseo-2/configure b/teseo-dist/teseo-2/configure
--- a/teseo-dist/teseo-2/configure
+++ b/teseo-dist/teseo-2/configure
@@ -308,8 +308,8 @@ ac_includes_default="\
 #if HAVE_UNISTD_H
 # include <unistd.h>
 #endif"
-
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT PKG_CONFIG GIMP_CFLAGS GIMP_LIBS GIMP_LIBDIR GTKADDONS_CFLAGS GTKADDONS_LIBS GTKADDONS_LIBDIR GTKEXTRA_CFLAGS GTKEXTRA_LIBS GTKEXTRA_LIBDIR NEWUOA_CFLAGS NEWUOA_LIBS NEWUOA_LIBDIR GETTEXT_PACKAGE INTLTOOL_DESKTOP_RULE INTLTOOL_DIRECTORY_RULE INTLTOOL_KEYS_RULE INTLTOOL_PROP_RULE INTLTOOL_OAF_RULE INTLTOOL_PONG_RULE INTLTOOL_SERVER_RULE INTLTOOL_SHEET_RULE INTLTOOL_SOUNDLIST_RULE INTLTOOL_UI_RULE INTLTOOL_XAM_RULE INTLTOOL_KBD_RULE INTLTOOL_XML_RULE INTLTOOL_XML_NOMERGE_RULE INTLTOOL_CAVES_RULE INTLTOOL_SCHEMAS_RULE INTLTOOL_THEME_RULE INTLTOOL_EXTRACT INTLTOOL_MERGE INTLTOOL_UPDATE INTLTOOL_PERL ICONV MSGFMT MSGMERGE XGETTEXT mkdir_p USE_NLS GMSGFMT CATALOGS CATOBJEXT DATADIRNAME GMOFILES INSTOBJEXT INTLLIBS PO_IN_DATADIR_TRUE PO_IN_DATADIR_FALSE POFILES POSUB MKINSTALLDIRS LOCALEDIR DATADIR LIBOBJS LTLIBOBJS'
+ 
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT PKG_CONFIG GIMP_CFLAGS GIMP_LIBS GIMP_LIBDIR GTKADDONS_CFLAGS GTKADDONS_LIBS GTKADDONS_LIBDIR GTKEXTRA_CFLAGS GTKEXTRA_LIBS GTKEXTRA_LIBDIR GTKDATABOX_CFLAGS GTKDATABOX_LIBS GTKDATABOX_LIBDIR NEWUOA_CFLAGS NEWUOA_LIBS NEWUOA_LIBDIR GETTEXT_PACKAGE INTLTOOL_DESKTOP_RULE INTLTOOL_DIRECTORY_RULE INTLTOOL_KEYS_RULE INTLTOOL_PROP_RULE INTLTOOL_OAF_RULE INTLTOOL_PONG_RULE INTLTOOL_SERVER_RULE INTLTOOL_SHEET_RULE INTLTOOL_SOUNDLIST_RULE INTLTOOL_UI_RULE INTLTOOL_XAM_RULE INTLTOOL_KBD_RULE INTLTOOL_XML_RULE INTLTOOL_XML_NOMERGE_RULE INTLTOOL_CAVES_RULE INTLTOOL_SCHEMAS_RULE INTLTOOL_THEME_RULE INTLTOOL_EXTRACT INTLTOOL_MERGE INTLTOOL_UPDATE INTLTOOL_PERL ICONV MSGFMT MSGMERGE XGETTEXT mkdir_p USE_NLS GMSGFMT CATALOGS CATOBJEXT DATADIRNAME GMOFILES INSTOBJEXT INTLLIBS PO_IN_DATADIR_TRUE PO_IN_DATADIR_FALSE POFILES POSUB MKINSTALLDIRS LOCALEDIR DATADIR LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -4530,6 +4530,52 @@ NEWUOA_LIBDIR=`$PKG_CONFIG --variable=libdir newuoa`
 ##manually made end
 
 
+##manually made
+GTKDATABOX_REQUIRED_VERSION=0.4.0.1
+
+  succeeded=no
+
+        echo "$as_me:$LINENO: checking for gtkdatabox >= $GTKDATABOX_REQUIRED_VERSION" >&5
+        echo $ECHO_N "checking for gtkdatabox >= $GTKDATABOX_REQUIRED_VERSION... $ECHO_C" >&6
+
+
+	if $PKG_CONFIG --exists "gtkdatabox >= $GTKDATABOX_REQUIRED_VERSION" ; then
+            echo "$as_me:$LINENO: result: yes" >&5
+            echo "${ECHO_T}yes" >&6
+            succeeded=yes
+
+            echo "$as_me:$LINENO: checking GTKDATABOX_CFLAGS" >&5
+            echo $ECHO_N "checking GTKDATABOX_CFLAGS... $ECHO_C" >&6
+            GTKDATABOX_CFLAGS=`$PKG_CONFIG --cflags "gtkdatabox >= $GTKDATABOX_REQUIRED_VERSION"`
+            echo "$as_me:$LINENO: result: $GTKDATABOX_CFLAGS" >&5
+            echo "${ECHO_T}$GTKDATABOX_CFLAGS" >&6
+
+            echo "$as_me:$LINENO: checking GTKDATABOX_LIBS" >&5
+            echo $ECHO_N "checking GTKDATABOX_LIBS... $ECHO_C" >&6
+            GTKDATABOX_LIBS=`$PKG_CONFIG --libs "gtkdatabox >= $GTKDATABOX_REQUIRED_VERSION"`
+            echo "$as_me:$LINENO: result: $GTKDATABOX_LIBS" >&5
+            echo "${ECHO_T}$GTKDATABOX_LIBS" >&6
+        else
+            GTKDATABOX_CFLAGS=""
+            GTKDATABOX_LIBS=""
+            ## If we have a custom action on failure, don't print errors, but
+            ## do set a variable so people can do so.
+            GTKDATABOX_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "gtkdatabox >= $GTKDATABOX_REQUIRED_VERSION"`
+            echo $GTKDATABOX_PKG_ERRORS
+        fi
+
+
+  if test $succeeded = yes; then
+     :
+  else
+     { { echo "$as_me:$LINENO: error: Library requirements (gtkdatabox >= $GTKDATABOX_REQUIRED_VERSION) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (gtkdatabox >= $GTKDATABOX_REQUIRED_VERSION) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+GTKDATABOX_LIBDIR=`$PKG_CONFIG --variable=libdir gtkdatabox`
+##manually made end
+
 
 GETTEXT_PACKAGE=teseo-2.0.9
 
@@ -7152,6 +7198,9 @@ s,@GTKADDONS_LIBDIR@,$GTKADDONS_LIBDIR,;t t
 s,@GTKEXTRA_CFLAGS@,$GTKEXTRA_CFLAGS,;t t
 s,@GTKEXTRA_LIBS@,$GTKEXTRA_LIBS,;t t
 s,@GTKEXTRA_LIBDIR@,$GTKEXTRA_LIBDIR,;t t
+s,@GTKDATABOX_CFLAGS@,$GTKDATABOX_CFLAGS,;t t
+s,@GTKDATABOX_LIBS@,$GTKDATABOX_LIBS,;t t
+s,@GTKDATABOX_LIBDIR@,$GTKDATABOX_LIBDIR,;t t
 s,@NEWUOA_CFLAGS@,$NEWUOA_CFLAGS,;t t
 s,@NEWUOA_LIBS@,$NEWUOA_LIBS,;t t
 s,@NEWUOA_LIBDIR@,$NEWUOA_LIBDIR,;t t
